=== txtjqm/starsXMLjava/xml/celCordStd2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.example.org"
            targetNamespace="http://www.example.org"
            elementFormDefault="qualified">
  <!-- generated from xml that works ok with jackson xml -->
  <xsd:element name="SkyobjColl">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="skyObjList">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="skyobj" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="name" type="xsd:string"/>
                    <xsd:element name="magnitude" type="xsd:float"/>
                    <xsd:element name="messier_num" type="xsd:string"/>
                    <xsd:element name="ngc_num" type="xsd:string"/>
                    <xsd:element name="messier_type" type="xsd:string"/>
                    <xsd:element name="dist_kly" type="xsd:string"/>
                    <xsd:element name="dist_ly" type="xsd:float"/>
                    <xsd:element name="ra" type="xsd:string"/>
                    <xsd:element name="decl" type="xsd:string"/>
                    <xsd:element name="celestCordParsed">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="raHour" type="xsd:float"/>
                          <xsd:element name="raMin" type="xsd:float"/>
                          <xsd:element name="raSec" type="xsd:float"/>
                          <xsd:element name="declDegr" type="xsd:float"/>
                          <xsd:element name="declMin" type="xsd:float"/>
                          <xsd:element name="declSec" type="xsd:float"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="skyType" type="skyTypeT"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="skyTypeT">
    <xsd:restriction base="xsd:string" >
        <xsd:enumeration value="messier" />
        <xsd:enumeration value="star" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== txtjqm/starsXMLjava/xml/outnewschema.stars.xml
<?xml version="1.0" encoding="UTF-8"?>
<SkyobjColl> <!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.example.org"
            xsi:schemaLocation="http://www.example.org celCordStd2.xsd"> -->
  <skyObjList>
    <skyobj skyType="star">
      <name>Sirius</name>
      <magnitude>-1.44</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>8.6</dist_ly>
      <ra>06h 45m</ra>
      <decl>-16.7°</decl>
      <celestCordParsed>
        <raHour>06</raHour>
        <raMin>45</raMin>
        <raSec>0</raSec>
        <declDegr>-16.7</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Canopus</name>
      <magnitude>-0.62</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>310</dist_ly>
      <ra>06h 24m</ra>
      <decl>-52.7°</decl>
      <celestCordParsed>
        <raHour>06</raHour>
        <raMin>24</raMin>
        <raSec>0</raSec>
        <declDegr>-52.7</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Rigil Kent.</name>
      <magnitude>-0.28</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>4.4</dist_ly>
      <ra>14h 40m</ra>
      <decl>-60.8°</decl>
      <celestCordParsed>
        <raHour>14</raHour>
        <raMin>40</raMin>
        <raSec>0</raSec>
        <declDegr>-60.8</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Arcturus</name>
      <magnitude>-0.05</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>36.7</dist_ly>
      <ra>14h 16m</ra>
      <decl>+19.2°</decl>
      <celestCordParsed>
        <raHour>14</raHour>
        <raMin>16</raMin>
        <raSec>0</raSec>
        <declDegr>19.2</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Vega</name>
      <magnitude>0.03</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>25.3</dist_ly>
      <ra>18h 37m</ra>
      <decl>+38.8°</decl>
      <celestCordParsed>
        <raHour>18</raHour>
        <raMin>37</raMin>
        <raSec>0</raSec>
        <declDegr>38.8</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Capella</name>
      <magnitude>0.08</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>42.2</dist_ly>
      <ra>05h 17m</ra>
      <decl>+46.0°</decl>
      <celestCordParsed>
        <raHour>05</raHour>
        <raMin>17</raMin>
        <raSec>0</raSec>
        <declDegr>46.0</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Rigel</name>
      <magnitude>0.18</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>770</dist_ly>
      <ra>05h 15m</ra>
      <decl>-8.2°</decl>
      <celestCordParsed>
        <raHour>05</raHour>
        <raMin>15</raMin>
        <raSec>0</raSec>
        <declDegr>-8.2</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Procyon</name>
      <magnitude>0.4</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>11.4</dist_ly>
      <ra>07h 39m</ra>
      <decl>+5.2°</decl>
      <celestCordParsed>
        <raHour>07</raHour>
        <raMin>39</raMin>
        <raSec>0</raSec>
        <declDegr>5.2</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Betelgeuse</name>
      <magnitude>0.45</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>430</dist_ly>
      <ra>05h 55m</ra>
      <decl>+7.4°</decl>
      <celestCordParsed>
        <raHour>05</raHour>
        <raMin>55</raMin>
        <raSec>0</raSec>
        <declDegr>7.4</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Achernar</name>
      <magnitude>0.45</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>144</dist_ly>
      <ra>01h 38m</ra>
      <decl>-57.2°</decl>
      <celestCordParsed>
        <raHour>01</raHour>
        <raMin>38</raMin>
        <raSec>0</raSec>
        <declDegr>-57.2</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Hadar</name>
      <magnitude>0.61</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>525</dist_ly>
      <ra>14h 04m</ra>
      <decl>-60.4°</decl>
      <celestCordParsed>
        <raHour>14</raHour>
        <raMin>04</raMin>
        <raSec>0</raSec>
        <declDegr>-60.4</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Altair</name>
      <magnitude>0.76</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>16.8</dist_ly>
      <ra>19h 51m</ra>
      <decl>+8.9°</decl>
      <celestCordParsed>
        <raHour>19</raHour>
        <raMin>51</raMin>
        <raSec>0</raSec>
        <declDegr>8.9</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Acrux</name>
      <magnitude>0.77</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>320</dist_ly>
      <ra>12h 27m</ra>
      <decl>-63.1°</decl>
      <celestCordParsed>
        <raHour>12</raHour>
        <raMin>27</raMin>
        <raSec>0</raSec>
        <declDegr>-63.1</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Aldebaran</name>
      <magnitude>0.87</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>65.1</dist_ly>
      <ra>04h 36m</ra>
      <decl>+16.5°</decl>
      <celestCordParsed>
        <raHour>04</raHour>
        <raMin>36</raMin>
        <raSec>0</raSec>
        <declDegr>16.5</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Spica</name>
      <magnitude>0.98</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>260</dist_ly>
      <ra>13h 25m</ra>
      <decl>-11.2°</decl>
      <celestCordParsed>
        <raHour>13</raHour>
        <raMin>25</raMin>
        <raSec>0</raSec>
        <declDegr>-11.2</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Antares</name>
      <magnitude>1.06</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>605</dist_ly>
      <ra>16h 29m</ra>
      <decl>-26.4°</decl>
      <celestCordParsed>
        <raHour>16</raHour>
        <raMin>29</raMin>
        <raSec>0</raSec>
        <declDegr>-26.4</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Pollux</name>
      <magnitude>1.16</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>33.7</dist_ly>
      <ra>07h 45m</ra>
      <decl>+28.0°</decl>
      <celestCordParsed>
        <raHour>07</raHour>
        <raMin>45</raMin>
        <raSec>0</raSec>
        <declDegr>28.0</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Fomalhaut</name>
      <magnitude>1.17</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>25.1</dist_ly>
      <ra>22h 58m</ra>
      <decl>-29.6°</decl>
      <celestCordParsed>
        <raHour>22</raHour>
        <raMin>58</raMin>
        <raSec>0</raSec>
        <declDegr>-29.6</declDegr>
        <declMin>0</declMin>
        <declSec>0</declSec>
      </celestCordParsed>
    </skyobj>
    <skyobj skyType="star">
      <name>Deneb</name>
      <magnitude>1.25</magnitude>
      <messier_num></messier_num>
      <ngc_num></ngc_num>
      <messier_type></messier_type>
      <dist_kly></dist_kly>
      <dist_ly>3200</dist_ly>
